### PR TITLE
Issue 182: Add Windows test to build

### PR DESCRIPTION
**Pull request by clyde-johnston**
This PR amends addresses issue #182. It amends the GH Actions workflow to:

- Include the Windows 2019 self-hosted runner with npcap pre-installed
- Separates the test and build into two steps, making the latter dependent on a push to `main`
- Regularizes the workflow to bring it inline with other OpenCyphal workflows

### CODE REVIEW

**Comment by clyde-johnston** [comment]
This PR is pending an investigation into the failure of the Windows test on the self-hosted runner with npcap pre-installed.  It fails to create a multicast group on the UDP socket on the loopback address. The WinSock error code is `[WSAEADDRNOTAVAIL]`.  Full logs can be found [here](https://github.com/OpenCyphal/yukon/actions/runs/5226057441/jobs/9436297402).

**Comment by clyde-johnston** [comment]
The workflow has been standardised with the other projects but the issue mentioned on Jun 12 [above](https://github.com/OpenCyphal/yukon/pull/400#issuecomment-1587134998) still persists.

**Comment by pavel-kirienko** [comment]
@silverv please look into this asap

**Review by silverv — APPROVED** [review]

**Comment by silverv** [comment]
It's time to merge!

**Pull request merged**
